### ISSUE TITLE
Entrega 1: Feedback da primeira entrega

### ISSUE THREAD

**Issue by lucascunhaiftm** [saulo8245/TrabalhosHtml#1]
**Correções: Links para os jogos não estão funcionando na página principal.
Imagens dos jogos não estão sendo carregadas.**
Nota da avaliação será disponibilizada em breve.

**Comment by saulo8245** [comment]
Ola Lucas como vc verificou la realmente as imagens da pagina nao estao
sendo carregas,fui olhar oq tinha acontecido para as imagens nao estarem
carregando, e percebir que o link das imagens que eu peguei nao estao mais
no Ar, os links parece que ficaram inativos com o tempo,se você quiser eu
mudo os links inativos do HTML para outros links ativos. Essa foi a
explicaçao o porque esta com aquele erro. Obrigado pela atençao!

Aluno: Saulo Barbosa de Oliveira
Ads 3

Em ter., 28 de abr. de 2020 às 19:34, Lucas Cunha <notifications@github.com>
escreveu:

**Comment by lucascunhaiftm** [comment]
Boa tarde,

Quando usamos imagens nos sites, podemos colocar links para endereços na
internet ou salvar as imagens localmente e informar seus endereços. No caso
das imagens locais no seu sistema, elas estavam referenciando absolutamente
os endereços, ou seja, endereço absoluto das imagens na sua máquina. Quando
fazemos isso, vc precisa colocar o endereço relativo a sua página com as
imagens e não caminho absoluto da sua máquina. Ex:

   - Img
      - foto1.png
      - foto2.png
      - HTML
      - index.html
      - jogo1.html

Nesse exemplo, se vc usar a imagem no index.html, no src da img você
colocará "../Img/foto1.png", e não o caminho absoluto,


Em qua., 29 de abr. de 2020 às 16:48, saulo8245 <notifications@github.com>
escreveu:
